// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgqqqcbrwhgzrxwbozmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNncXFxY2Jyd2hnenJ4d2Jvem13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjQ0NjQsImV4cCI6MjA3MTEwMDQ2NH0.1Ln4PBuSlxs_XJkHqApjnTRCa4zgUh0X76KV0r2WnRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});